### ISSUE TITLE
How to use the plct-gem5

### ISSUE THREAD

**Issue by lifei0919** [plctlab/plct-gem5#10]
Dear Professor, I'm sorry to take up your time. Recently, I needed to use gem5 to test the performance of the program written by RISC-V assembly instructions. After testing, I have successfully installed plct-gem5 at present, as shown below:
![image](https://user-images.githubusercontent.com/80608803/191636978-ecd9276e-4d87-44d6-afc0-7f830e1b0218.png)

But the following error is displayed when I execute a binary file
<img width="415" alt="image" src="https://user-images.githubusercontent.com/80608803/191637132-3580868b-89f7-4ab0-ae23-83f193284529.png">

Here's how I generated the file:
1. riscv64-unknown-elf-as -march=rv64gcv --mabi=lp64d finite_rv.S -o finite_rv.o
2. riscv64-unknown-elf-gcc -c test_finite.c -o test_finite.o
3. riscv64-unknown-elf-gcc -static finite_rv.o addtc_rv.o test_finite.o -o finite

If I use the spike simulator perform this instruction: **spike --varch="vlen:256,elen:64,vstartalu:0" --isa=RV64GCV pk ./finite**, the file can be executed correctly, the result as following figure:
<img width="271" alt="image" src="https://user-images.githubusercontent.com/80608803/191637701-002be73a-f4f8-4032-b135-1e3815f93702.png">

Here is the code for both files
**1. finite_rv.S:**
.section .text, "ax", "progbits"       
        .align 4        
        .section .text  
        .globl _rv_finite       
_rv_finite:      
        fmv.x.d a0,fa0  
        li t0,2047      
        slli t0,t0,0x34 
        and a0,a0,t0    
        sub a0,a0,t0    
        seqz a0,a0
        xor a0,a0,0x1   
        fcvt.d.l fa0,a0
        ret
        .align 4

**2.test_finite.c**
#include <stdio.h>
double _rv_finite(double x); 
typedef union
{
     double d;
     unsigned long int l;
}DL;
int main(void)
{
        DL x8; 
        double x1 = 1.57;
        double x2 = 100.125;
        double x3 = -0.785;
        double x4 = 3.14;
        double x5 = 0;
        double y1,y2,y3,y4,y5,y6,y7,y8;
        y1=_rv_finite(x1);
        y2=_rv_finite(x2);
        y3=_rv_finite(x3);
        y4=_rv_finite(x4);
        y5=_rv_finite(x5);
        printf("%lf\t%lf\n",x1,y1);
        printf("%lf\t%lf\n",x2,y2);
        printf("%lf\t%lf\n",x3,y3);
        printf("%lf\t%lf\n",x4,y4);
        printf("%lf\t%lf\n",x5,y5);
        return 0;
}

I really hope to get your help. Good luck

**Comment by ksco** [comment]
Your Python script cannot contain any non-ASCII characters, otherwise gem5 will throw the error.

**Comment by lifei0919** [comment]
These two files were generated directly after I configured the environment. I didn't make any changes. I just tested **main.py** and **codecs.py** separately and found no errors thrown.
![image](https://user-images.githubusercontent.com/80608803/191647491-06690f11-df52-4eab-a9a5-378ca4266bd8.png)
![image](https://user-images.githubusercontent.com/80608803/191647781-4715052e-f02a-4e15-b92a-a0c3bb62caf9.png)

**Comment by ksco** [comment]
I believe ../Corretest/pre is a Python file, right?

**Comment by lifei0919** [comment]
This file of **../Corretest/pretest/finite**is not a Python file, it is the above C program and RISC-V assembler, compiled executable file, generated as follows：
riscv64-unknown-elf-as -march=rv64gcv --mabi=lp64d **finite_rv.S** -o finite_rv.o
riscv64-unknown-elf-gcc -c **test_finite.c** -o test_finite.o
riscv64-unknown-elf-gcc -static finite_rv.o addtc_rv.o test_finite.o -o **finite**

**Comment by lifei0919** [comment]
Hello, it's ready to use. Thank you

**Comment by ksco** [comment]
Please read gem5's official documentation before starting to use it. https://www.gem5.org/getting_started/
