### ISSUE TITLE
对RISC-V向量扩展指令的支持进度

### ISSUE THREAD

**Issue by lifei0919** [plctlab/plct-gem5#15]
老师您好：
请问gem5目前对RISC-V向量扩展指令还有多少没有支持？因为想通过gem5对RISC-V汇编程序进行性能测试，但是发现还有些RISC-V向量指令不能正确认识。所以想询问您：对RISC-V向量指令全部支持的计划时间，或者说怎么对下载后的plct-gem5源码进行修改，使之对目前我们涉及的RISC-V的向量指令进行有效支持。非常感谢你们为该项目付出的努力。

**Comment by ksco** [comment]
我们还在开发的早期阶段，如果您有意贡献，可以直接提交 PR，谢谢！

**Comment by lifei0919** [comment]
您好，我现在是论文审稿人想要我完善gem5对我测试程序内的部分向量指令的支持，以进行充分性能测试。但是时间有限，请问有没有具体的开发文档，以在短时间内实现对涉及的向量指令支持。或者我应该从哪里入手，因为之前对该方面知识比较欠缺，或者说实现的难度是否困难，非常感谢你们为该项目付出的努力。期待您的回复。

**Comment by huxuan0307** [comment]
> 您好，我现在是论文审稿人想要我完善gem5对我测试程序内的部分向量指令的支持，以进行充分性能测试。但是时间有限，请问有没有具体的开发文档，以在短时间内实现对涉及的向量指令支持。或者我应该从哪里入手，因为之前对该方面知识比较欠缺，或者说实现的难度是否困难，非常感谢你们为该项目付出的努力。期待您的回复。

目前rvv-cpu分支已经实现~95%的向量指令，仅有vslide*，vle*ff，vcompress这三类指令没实现。可以直接通过configs/se.py使用，cpu type可以指定AtomicCPU、MinorCPU和O3CPU，这些CPU模型全部做了支持。我们的TODO list里还有latency没有分类实现，用现在的latency设定来测试性能毫无意义，暂时需要DIY。

**Comment by lifei0919** [comment]
好的，谢谢您~

**Comment by ZqMark** [comment]
您好，请问你们这边有实现RVV Segment load/store指令的计划吗？，我自己尝试实现，还未能通过功能测试。

**Comment by wang-jiaolong** [comment]
> 

同学您好，最近我也在做RVV相关的实验，想问下在gem5下是否有合适的性能测试方案。一直没有找到合适的仿真环境，准备尝试下gem5，能否冒昧的请教一下。

**Comment by lifei0919** [comment]
可以，您看怎么方便沟通。


LIFEI
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "plctlab/plct-gem5"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月15日(星期三) 上午9:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [plctlab/plct-gem5] 对RISC-V向量扩展指令的支持进度 (Issue #15)





   
同学您好，最近我也在做RVV相关的实验，想问下在gem5下是否有合适的性能测试方案。一直没有找到合适的仿真环境，准备尝试下gem5，能否冒昧的请教一下。

**Comment by wang-jiaolong** [comment]
> 可以，您看怎么方便沟通。 LIFEI ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "plctlab/plct-gem5" ***@***.***&gt;; 发送时间:&nbsp;2023年3月15日(星期三) 上午9:26 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [plctlab/plct-gem5] 对RISC-V向量扩展指令的支持进度 (Issue #15) 同学您好，最近我也在做RVV相关的实验，想问下在gem5下是否有合适的性能测试方案。一直没有找到合适的仿真环境，准备尝试下gem5，能否冒昧的请教一下。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


联系方式貌似被和谐掉了，我更新了下个人邮箱，您可以在我的主页中看到。
