### ISSUE TITLE
Regarding changing of vector lengths for gem5 with RISC-V Vector

### ISSUE THREAD

**Issue by soniab** [plctlab/plct-gem5#20]
I am using gem5 for RISC-V Vector and want to do the experimentation with different vector lengths. I am using se.py for running my experiments. But I could not find the option to change vector lengths. I also tried to look at the --param parameters but could not find any option in that too. Can you please guide me on this?

**Comment by ksco** [comment]
We don't support changing VLEN yet, it's hardcoded now.

**Comment by soniab** [comment]
Can you please direct me to the files where I can change that hard-coded value for vector lengths and rebuild Gem5?

**Comment by ksco** [comment]
It's in [here](https://github.com/plctlab/plct-gem5/blob/rvv-cpu/src/arch/riscv/regs/vector.hh#L49-L53), however, we haven't tested it under other VLENs yet, change VLEN may causing a segfault.

Btw Hoa is adding configurable VLEN in https://github.com/plctlab/plct-gem5/pull/21.

**Comment by soniab** [comment]
Thank you very much. I will try to do experiments by changing the vector length.

**Comment by ksco** [comment]
If you have further discussion, please open a new issue.
