### ISSUE TITLE
Vrgather指令实现是否有问题？

### ISSUE THREAD

**Issue by ptzheng** [plctlab/plct-gem5#22]
constexpr uint32_t vd_eewb = sizeof(ElemType);
    constexpr uint32_t vs2_eewb = sizeof(ElemType);
    constexpr uint32_t vs1_eewb = sizeof(IndexType);
    constexpr bool vs1_split = vd_eewb > vs1_eewb;
    const int8_t lmul = vtype_vlmul(vtype);
    const int8_t vs1_emul = lmul +
        (vs1_split ? -(vs2_eewb / vs1_eewb) : vs1_eewb / vs2_eewb);

假设sew = 32，LMUL = 1，对于vrgather.vv指令，vd_eewb=vs2_eewb=vs1_eewb=4, vs1_split = false, lmul = 0b000，则计算出的vs1_emul = 0b001，即vs1_EMUL = 2。但实际上vs1_EMUL应该为1。

**Comment by huxuan0307** [comment]
确实，这里的计算我推敲得还不够仔细。不过我观察了多种情况生成的microop，并没有发现冗余的microop，也没有发现计算错误，可能是被micro vl的条件限制了。
您方便提个PR吗？提供一个正确计算的方法，我们测试之后会尽快合并。

**Comment by huxuan0307** [comment]
> 确实，这里的计算我推敲得还不够仔细。不过我观察了多种情况生成的microop，并没有发现冗余的microop，也没有发现计算错误，可能是被micro vl的条件限制了。 您方便提个PR吗？提供一个正确计算的方法，我们测试之后会尽快合并。

计算错误指的是macroop运行的结果

**Comment by ptzheng** [comment]
> > 确实，这里的计算我推敲得还不够仔细。不过我观察了多种情况生成的microop，并没有发现冗余的microop，也没有发现计算错误，可能是被micro vl的条件限制了。 您方便提个PR吗？提供一个正确计算的方法，我们测试之后会尽快合并。
> 
> 计算错误指的是macroop运行的结果

没有冗余的原因是在“for (uint8_t i = 0; i < std::max(vs1_vregs, vd_vregs) && micro_vl > 0;” 判断中，只有当指令为vrgatherei16.vv且sew=8时，std::max(vs1_vregs, vd_vregs) = vs1_regs，由于浮点实现的最小sew=32，故上面情况不会出现。若要严谨起见，可将
const int8_t vs1_emul = lmul +
(vs1_split ? -(vs2_eewb / vs1_eewb) : vs1_eewb / vs2_eewb);
修改为：
const int8_t vs1_emul = lmul + log2(vs1_eewb / vs2_eewb));
