### ISSUE TITLE
RVV指令 segment load/store指令的支持

### ISSUE THREAD

**Issue by ZqMark** [plctlab/plct-gem5#29]
您好，请问你们这边有实现segment load/store指令的计划吗？我这边尝试实现，但还没能通过功能测试。

**Comment by huxuan0307** [comment]
个人觉得segment访存指令与微架构强相关，我想做，但是暂时没有合适的实现方案。请问你对segment访存指令的实现有什么见解吗？咱们可以多多交流。

**Comment by huxuan0307** [comment]
个人觉得segment访存指令与微架构强相关，我想做，但是暂时没有合适的实现方案。请问你对segment访存指令的实现有什么见解吗？咱们可以多多交流。

**Comment by ZqMark** [comment]
我这里尝试了几种拆分microop的方式：1，NF（NFIELDS）为循环最外层，对每个micro_vl按Vlstride的访存方式，相当于NFIELDS是Vlstride跨步步长进行访存，2，NF（NFIELDS）为循环最里层，对micro_vl的每个元素进行遍历，一个元素分配NFIELDS在不同的寄存器上。上面两种microop设置方式都涉及了寄存器编号需要对齐的问题，这个是根据emul进行寄存器编号的计算。
这两种microop的拆分方式我都试了但是在执行gem5.fast时，运行程序不能跑出结果，但执行gem5.debug可以跑出结果，但遇到如下图所示一个报错，目前还没解决，gem5和cpu的一些知识不是很了解，不知道你们有没有什么看法
![图片](https://user-images.githubusercontent.com/54583768/211526278-e37cfb01-d4ce-42c9-81c7-240b1df451dc.png)

**Comment by ZqMark** [comment]
您好，我这边已经完成了Segment访存指令的支持，感谢你们的开源工作。
