### ISSUE TITLE
Any plans to merge to gem5 upstream? 有向gem5上游合并的计划吗？

### ISSUE THREAD

**Issue by zinechant** [plctlab/plct-gem5#4]
As title. 如题.

**Comment by ksco** [comment]
有的，我们已经开源了新的实现，可以看一下 rvv-cpu 分支。目前实现的指令还不多，等实现完整后我们会尝试 upstream。

**Comment by YuShuanHsieh** [comment]
不好意思，想請問一下，原本這個 repo 是從 RALC88/gem5 fork 出來。不過後來為什麼會移除掉 vector engine 的設計呢？

**Comment by ksco** [comment]
原实现（RALC88/gem5 fork）只支持 MinorCPU 模型，且对 MinorCPU 的代码侵入较大。新实现是完全重写的，支持所有的 CPU 模型，实现上更符合 gem5 的设计准则。
