### ISSUE TITLE
try rvv-cpu

### ISSUE THREAD

**Issue by PPParticle** [plctlab/plct-gem5#7]
你好！注意到 plct 实验室关于 gem5 的工作有了新的进展 (将原来类似于协处理器的 vector_engine 集成到了 cpu 中)。我想尝试相关的测试，但不同于之前的 vector_engine，新的工作在 configs\example 之下没有类似之前的 python 脚本，且在 src\cpu 中没有类似之前 vector_engine 的一些 .py 代码，有修改的部分仅是 src\arch\riscv 中，但对于这一部分的改动，我不知道如何进行测试。能指导我一些测试方法或者如何进行相关学习吗？

**Comment by ksco** [comment]
谢谢关注，你可以直接使用自带的 [se.py](https://github.com/plctlab/plct-gem5/blob/rvv-cpu/configs/example/se.py) 来运行用户态程序。

**Comment by PPParticle** [comment]
我尝试了一下，之前 vector_engine 可以跑通的程序
`$ build/RISCV/gem5.opt configs/example/se.py --cpu-type RiscvAtomicSimpleCPU --cmd ../gem5-test/rvv-test`

但是，显示报错
**** REAL SIMULATION ****
build/RISCV/sim/simulate.cc:194: info: Entering event queue @ 0.  Starting simulation...
build/RISCV/arch/riscv/faults.cc:189: panic: Unknown instruction 0x03068407 at pc (0x10d42=>0x10d46).(0=>1)
Memory Usage: 680956 KBytes
Program aborted at tick 123000

通过sipke模拟器分步调试到这一句发现，程序只是运行到 bbl loader 就结束了
`$ spike --isa=rv64gcv -d pk ../gem5-test/rvv-test
: until pc 0 10d42
bbl loader
`
所以，我不知道到底该如何测试

**Comment by ksco** [comment]
现在还在活跃开发阶段，还有一些指令未实现。

**Comment by PPParticle** [comment]
saxpy:
    vsetvli a4, a0, e32, m1, ta,ma
    vle32.v v0, (a1)
    sub a0, a0, a4
    slli a4, a4, 2
    add a1, a1, a4
    vle32.v v8, (a2)
    vfmacc.vf v8, fa0, v0
    vse32.v v8, (a2)
    add a2, a2, a4
    bnez a0, saxpy
    ret

因为，我使用的指令都是较为基础的 rvv 指令，所以不知道是不是我的环境或者运行选项的问题。

**Comment by ksco** [comment]
> panic: Unknown instruction 0x03068407 at pc (0x10d42=>0x10d46).(0=>1)

您上面的这个报错，`0x03068407` 对应的汇编是：`vle8ff.v v8, (a3)`，这条指令我们还没有实现。

**Comment by PPParticle** [comment]
感谢您的回答，更改代码后，可以跑通了。

**Comment by ksco** [comment]
那我就关闭这个 issue 了，后续有需要讨论的可以另开。
