### ISSUE TITLE
After plct-gem5 is installed, there is no riscv_vector_engine.py file

### ISSUE THREAD

**Issue by lifei0919** [plctlab/plct-gem5#9]
Dear researcher, I have met a problem recently and would like to ask for your advice.
Today I configured the environment of plct-gem5, but found no this file: riscv_vector_engine.py, below is my execution RISC-V assembly process of binary files.

![b5073d2e257e1e33d33a53174c7acda](https://user-images.githubusercontent.com/80608803/191451374-0f0a24f6-0ad0-45ff-b848-2260eaf30665.jpg)

After checking, the file does not exist in the following directory either
![e76b0480728c67b2999c51b5d40905f](https://user-images.githubusercontent.com/80608803/191451630-b054fda2-0a4d-4e35-a09a-45379050057d.jpg)

During the environment configuration process, the following message is displayed when the "scons build/RISCV/gem5.opt" command is executed.

![6029fe183685f2a5f236c3e5aa763d3](https://user-images.githubusercontent.com/80608803/191452253-e6c1120b-2f0a-49aa-ad7a-08bd88f169cd.jpg)

**Comment by ksco** [comment]
You can use se.py to run the user mode program.
